const jwt = require('jsonwebtoken');
const User = require('../models/User');

// In-memory map of userId -> Set of connected socket ids.
// A user can have multiple sockets open (e.g. two devices), so we track a set,
// not a single id, and only mark them offline once ALL their sockets disconnect.
const onlineUsers = new Map();

const userRoom = (userId) => `user:${userId}`;

/**
 * Authenticates a connecting socket using the same JWT issued by /api/auth/login.
 * Client must connect with: io(URL, { auth: { token: '<jwt>' } })
 */
const socketAuthMiddleware = async (socket, next) => {
  try {
    const token = socket.handshake.auth?.token;
    if (!token) return next(new Error('Not authorized, no token'));

    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const user = await User.findById(decoded.id).select('-password');
    if (!user) return next(new Error('Not authorized, user not found'));

    socket.userId = user._id.toString();
    socket.username = user.username;
    next();
  } catch (error) {
    next(new Error('Not authorized, token invalid'));
  }
};

const initCallSignaling = (io) => {
  io.use(socketAuthMiddleware);

  io.on('connection', async (socket) => {
    const { userId } = socket;

    // Track this socket and mark the user online (only on their first connection).
    if (!onlineUsers.has(userId)) onlineUsers.set(userId, new Set());
    const wasOffline = onlineUsers.get(userId).size === 0;
    onlineUsers.get(userId).add(socket.id);
    socket.join(userRoom(userId));

    if (wasOffline) {
      await User.findByIdAndUpdate(userId, { isOnline: true });
    }

    // ── Call invite: caller -> callee ──
    // channelName should be generated by the caller (e.g. sorted `${id1}_${id2}`)
    // and used by both sides to fetch their Agora token via POST /api/agora/token.
    socket.on('call:invite', async ({ toUserId, channelName, callType }) => {
      if (!toUserId || !channelName) return;

      // Server-side friendship check — the frontend already hides the call
      // button for non-friends, but a client could still emit this event
      // directly, so we don't rely on that alone.
      const me = await User.findById(userId).select('friends');
      const isFriend = me?.friends?.some((f) => f.toString() === toUserId);
      if (!isFriend) {
        socket.emit('call:not_friends', { toUserId, channelName });
        return;
      }

      const calleeOnline = onlineUsers.has(toUserId) && onlineUsers.get(toUserId).size > 0;
      if (!calleeOnline) {
        socket.emit('call:unavailable', { toUserId, channelName });
        return;
      }

      io.to(userRoom(toUserId)).emit('call:incoming', {
        fromUserId: userId,
        fromUsername: socket.username,
        channelName,
        callType: callType === 'video' ? 'video' : 'audio',
      });
    });

    // ── Callee accepts ──
    socket.on('call:accept', ({ toUserId, channelName }) => {
      if (!toUserId || !channelName) return;
      io.to(userRoom(toUserId)).emit('call:accepted', {
        fromUserId: userId,
        channelName,
      });
    });

    // ── Callee rejects ──
    socket.on('call:reject', ({ toUserId, channelName, reason }) => {
      if (!toUserId || !channelName) return;
      io.to(userRoom(toUserId)).emit('call:rejected', {
        fromUserId: userId,
        channelName,
        reason: reason || 'declined',
      });
    });

    // ── Caller cancels before the callee answers ──
    socket.on('call:cancel', ({ toUserId, channelName }) => {
      if (!toUserId || !channelName) return;
      io.to(userRoom(toUserId)).emit('call:cancelled', {
        fromUserId: userId,
        channelName,
      });
    });

    // ── Either side ends an in-progress call ──
    socket.on('call:end', ({ toUserId, channelName }) => {
      if (!toUserId || !channelName) return;
      io.to(userRoom(toUserId)).emit('call:ended', {
        fromUserId: userId,
        channelName,
      });
    });

    socket.on('disconnect', async () => {
      const sockets = onlineUsers.get(userId);
      if (!sockets) return;
      sockets.delete(socket.id);

      if (sockets.size === 0) {
        onlineUsers.delete(userId);
        await User.findByIdAndUpdate(userId, {
          isOnline: false,
          lastSeen: new Date(),
        });
      }
    });
  });
};

module.exports = { initCallSignaling };